# Generated by Django 6.1 on 2026-08-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название товара')),
                ('product_code', models.CharField(max_length=100, unique=True, verbose_name='Код товара')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('memory_capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Объем памяти')),
                ('screen_diagonal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Диагональ экрана')),
                ('screen_resolution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Разрешение дисплея')),
                ('regular_price', models.IntegerField(blank=True, null=True, verbose_name='Цена обычная')),
                ('promo_price', models.IntegerField(blank=True, null=True, verbose_name='Цена акционная')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Кол-во отзывов')),
                ('photos', models.JSONField(default=list, verbose_name='Все фото товара')),
                ('specifications', models.JSONField(default=dict, verbose_name='Характеристики товара (словарь)')),
            ],
        ),
    ]
